# Generated by Django 3.1.2 on 2020-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201024_1501'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='webapp.Photo', verbose_name='Избраное'),
        ),
    ]
